### ISSUE TITLE
好吧。

### ISSUE THREAD

**Issue by xinghui0000** [sikaozhe1997/Xin-Yue#439]
好吧

**Comment by Xbigfat** [comment]
大悲哀

**Comment by ayaservice** [comment]
被封，你不会翻墙吗？

**Comment by bifan-wei** [comment]
以后如果你发生这种事情，希望大家也是这么说的

**Comment by XhstormR** [comment]
斯德哥尔摩 了解一下

**Comment by chewenkai** [comment]
真 **·** 利己主义

**Comment by kitety** [comment]
等到github被墙墙了,那就开发很困难了.

**Comment by ayaservice** [comment]
社会主义的码农不需要警察了，因为码农都学会了自己逮捕自己

**Comment by chewenkai** [comment]
They first came for the Communists,
and I didn't speak up
because I wasn't a Communist.
Then they came for the Jews,
and I didn't speak up
because I wasn't a Jew.
Then they came for the trade unionists,
and I didn't speak up
because I wasn't a trade unionist.
Then they came for the Catholics,
and I didn't speak up
because I was a Protestant.
Then they came for me,
but by that time,
there was no one left to speak up.
中文
纳粹杀共产党时，
我没有出声
——因为我不是共产党员；
接着他们迫害犹太人，
我没有出声
——因为我不是犹太人；
然后他们杀工会成员，
我没有出声
——因为我不是工会成员；
后来他们迫害天主教徒，
我没有出声
——因为我是新教徒；
最后当他们开始对付我的时候，
已经没有人能站出来为我发声了

**Comment by zhichiyuexin** [comment]
不会翻墙当什么程序员?你连android开发环境都搭不起来

**Comment by ayaservice** [comment]
政治乃众人之事，在哪里都有讨论的自由，除非地主不允许，毕竟私人地方。GitHub没有反对，当然就可以，他人，爱看不看。

**Comment by huoqiangf** [comment]
影响了多少人你倒是说说啊？
我倒是觉得封了以后网络环境倒是会净化不少。。。之后issues就能用来好好讨论问题了。。。

真的，跪求赶紧封？

楼主想请教一下你还觉得什么事情会导致GitHub被封？我赶紧去干

**Comment by ayaservice** [comment]
公共区域的讨论，只要在法律和区域规则框架内，你不喜欢，就不要看，可以屏蔽之，但从来没有叫别人闭嘴的道理。

**Comment by goldimax** [comment]
讲道理 如果你遇到冤屈了 你找到了一个可以说话的地方 记录下了你说的 别人却怕社区被牵连而向你倒苦水 你能去哪里说理呢……
现在人都不能明辨是非了吗？

**Comment by Vargnatt** [comment]
不能因为你建立在幻想上的诉求影响我们合理表达的权利。

**Comment by shanezhiu** [comment]
原来Twitter说的就是这事儿啊!

**Comment by djl394922860** [comment]
看来我是知道的有些晚 魔幻之至！！！

**Comment by liangsongyou** [comment]
哈哈，自私的更高境界就是堂而皇之的说出来而不自知

**Comment by PGGGX** [comment]
WHY NOT，作为为数不多的平台能发声已经可悲了。

**Comment by nullpointerxyz** [comment]
求赶紧墙掉，以后就看不到你这样的辣鸡了

**Comment by crescendo007** [comment]
中共体制，是烂到根里了。尤其是在习包子上台以后，整个中国被他治理的乌烟瘴气。他上台以后，除了治理贪官，还有什么政绩？另外治理官场腐败，本来就是一个政府理所应当的事情，结果变成了习包子的政绩。

**Comment by guodong** [comment]
@crescendo007 已截图发给相关部门

**Comment by moonwater** [comment]
这些自私的forker，搬代码回去来建造这个高科技的牢笼．
